// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { User } from "./User";

/**
 * The one object page code reads on its first line. Per-request values belong
 * here; there is no `/api/config` and no value passed through JS (R65).
 */
export type Config = { assetsOrigin: string, loginPath: string, 
/**
 * `None` on an unauthenticated page, where `<les-bar>` renders no account
 * at all rather than an empty one — registry's launcher is the case.
 */
user: User | null, 
/**
 * R75's launcher root. EMPTY means absent, which is what the bar's own
 * truthiness check treats as "render the app token as text, not a dead
 * link" — so the Rust side and the element agree without a second
 * convention.
 */
launcherUrl: string, 
/**
 * R73's end-session route. Empty renders no logout control, which is how
 * the element ships before the route exists.
 */
logoutPath: string, };
