// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Who is looking at the page, for `<les-account>` (R72). Server-side, from the
 * session — the element reads no cookie and no token of its own (§12.17).
 */
export type User = { name: string, portrait: string | null, };
