//! The theme palettes and the browser LOADER, carried in a crate (R117).
//!
//! This crate replaces the Phase-A server-side `theme_override_link`: there is
//! no per-request theme link built in Rust any more. Instead:
//!
//! - The DEFAULT palette and a standard bundled set ship here as committed
//!   consts (emitted by `common-ui-e`'s `build.sh`), served by each app at
//!   `/assets/theme-<name>/palette.css`.
//! - The [`LOADER_JS`] is a browser script, also crate-carried, served at
//!   `/assets/theme-loader.js` and linked from the shell with a classic
//!   `<script>` in `<head>`. It reads the SINGLE `les_theme` cookie and swaps
//!   the default `<link>` for a non-default choice.
//!
//! # The cookie contract (owned by the loader)
//!
//! `les_theme=<name>` selects a crate-bundled palette (app-served, no hash);
//! `les_theme=<name>@<hash>` selects a hashed palette on Garage
//! (`{ASSETS_ORIGIN}/common-ui@<hash>/theme-<name>/palette.css`). No cookie, or
//! `name == "default"`, leaves the shell's default `<link>` in place.
//!
//! The charset rules that used to live in Rust ([`is_theme_name`],
//! [`is_theme_version`]) now live in the loader (JS) — that is the security
//! boundary, and it is tested in `common-ui-e`'s browser suite. They are kept
//! here ONLY as the reference definition of the two charsets the loader
//! enforces; nothing in this crate reflects a cookie into a URL.

/// The theme cookie name the picker writes and the loader reads.
pub const THEME_COOKIE: &str = "les_theme";

/// The browser theme loader (classic head script). Served at
/// `/assets/theme-loader.js`. Emitted from `common-ui-e/src/theme-loader.js`.
pub const LOADER_JS: &str = include_str!("assets/theme-loader.js");

/// The default palette. Served at `/assets/theme-default/palette.css` and
/// linked by the shell as the pre-swap default.
pub const DEFAULT_PALETTE: &str = include_str!("assets/theme-default/palette.css");

/// `sha384-…` integrity of [`DEFAULT_PALETTE`], for the shell's default
/// palette `integrity=` (the `sri_palette_css` build marker). Emitted with no
/// trailing newline.
pub const SRI_DEFAULT_PALETTE: &str = include_str!("assets/theme-default/palette.css.sri");

// Every bundled palette as `PALETTES: &[(&str, &str)]` (name, css), sorted by
// name, `default` included. Generated by build.sh so the set is never
// hand-maintained: a palette added to the bundled set appears here on the next
// emit with no edit to this file.
include!("palettes.rs");

/// The CSS for one bundled palette by name, or `None`. A consumer serving
/// `/assets/theme-<name>/palette.css` looks the bytes up here.
pub fn palette(name: &str) -> Option<&'static str> {
    PALETTES
        .iter()
        .find(|(n, _)| *n == name)
        .map(|(_, css)| *css)
}

/// `^[0-9a-f]{12}$` — the reference definition of the hash charset the loader
/// enforces. A common-ui release hash, lowercase hex, exactly 12.
pub fn is_theme_version(v: &str) -> bool {
    v.len() == 12 && v.bytes().all(|b| matches!(b, b'0'..=b'9' | b'a'..=b'f'))
}

/// `^[a-z0-9-]{1,40}$` — the reference definition of the name charset the
/// loader enforces. No dot, slash, quote, uppercase or angle bracket survives.
pub fn is_theme_name(n: &str) -> bool {
    (1..=40).contains(&n.len())
        && n.bytes()
            .all(|b| matches!(b, b'a'..=b'z' | b'0'..=b'9' | b'-'))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn default_is_bundled_and_matches_the_const() {
        assert_eq!(palette("default"), Some(DEFAULT_PALETTE));
        // The bundled set is sorted, default included, and non-empty.
        assert!(!PALETTES.is_empty());
        assert!(PALETTES.iter().any(|(n, _)| *n == "default"));
        let mut sorted = PALETTES.to_vec();
        sorted.sort();
        assert_eq!(PALETTES, sorted.as_slice(), "PALETTES must be sorted");
    }

    #[test]
    fn every_bundled_name_passes_the_name_charset() {
        for (name, css) in PALETTES {
            assert!(is_theme_name(name), "bundled name {name:?} is not valid");
            assert!(!css.is_empty(), "bundled palette {name:?} is empty");
        }
    }

    #[test]
    fn loader_and_default_sri_are_present() {
        assert!(
            !LOADER_JS.is_empty(),
            "loader is empty — did build.sh emit it?"
        );
        assert!(
            LOADER_JS.contains("les_theme"),
            "loader must read the cookie"
        );
        assert!(
            SRI_DEFAULT_PALETTE.starts_with("sha384-"),
            "default palette SRI is not sha384-…: {SRI_DEFAULT_PALETTE:?}"
        );
        assert_eq!(SRI_DEFAULT_PALETTE.trim(), SRI_DEFAULT_PALETTE);
    }

    #[test]
    fn charset_rules_reject_hostile_values() {
        for bad in ["..", "a/b", "A", "\"><script>", "", &"a".repeat(41)] {
            assert!(!is_theme_name(bad), "{bad:?} must be rejected");
        }
        for bad in ["deadbeef", "DEADBEEF0000", "g00000000000", "../x", ""] {
            assert!(!is_theme_version(bad), "{bad:?} must be rejected");
        }
        assert!(is_theme_name("neo-brutal"));
        assert!(is_theme_version("0123456789ab"));
    }
}
