// GENERATED by common-ui-e/build.sh — do not edit by hand.
// include!()d into lib.rs, so outer comments only (no //! here).
/// Every bundled palette, `(name, css)`, sorted, `default` included.
pub const PALETTES: &[(&str, &str)] = &[
    ("contrast", include_str!("assets/theme-contrast/palette.css")),
    ("default", include_str!("assets/theme-default/palette.css")),
    ("forest", include_str!("assets/theme-forest/palette.css")),
    ("glassmorph", include_str!("assets/theme-glassmorph/palette.css")),
    ("graphite", include_str!("assets/theme-graphite/palette.css")),
    ("ink", include_str!("assets/theme-ink/palette.css")),
    ("material3", include_str!("assets/theme-material3/palette.css")),
    ("midnight", include_str!("assets/theme-midnight/palette.css")),
    ("neo-brutal", include_str!("assets/theme-neo-brutal/palette.css")),
    ("neumorph", include_str!("assets/theme-neumorph/palette.css")),
    ("nord", include_str!("assets/theme-nord/palette.css")),
    ("ocean", include_str!("assets/theme-ocean/palette.css")),
    ("sand", include_str!("assets/theme-sand/palette.css")),
    ("slate", include_str!("assets/theme-slate/palette.css")),
    ("soft", include_str!("assets/theme-soft/palette.css")),
    ("swiss", include_str!("assets/theme-swiss/palette.css")),
];
